// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIvcTcNAvu1GZsvsJMEPBrgCAkBAEOxA',
    appId: '1:110447241239:web:09a7ce0e85f738159b9452',
    messagingSenderId: '110447241239',
    projectId: 'instaclone-b0c32',
    authDomain: 'instaclone-b0c32.firebaseapp.com',
    storageBucket: 'instaclone-b0c32.appspot.com',
    measurementId: 'G-P1EBQNG2W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwykom5Wg4QvTGS2kuXLqOQ2wkWjGIOCw',
    appId: '1:110447241239:android:7e133761b4cb095e9b9452',
    messagingSenderId: '110447241239',
    projectId: 'instaclone-b0c32',
    storageBucket: 'instaclone-b0c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKOgwg9iKKSv5aBu-hOloQNrKttad3hbw',
    appId: '1:110447241239:ios:80e80caf819c07cb9b9452',
    messagingSenderId: '110447241239',
    projectId: 'instaclone-b0c32',
    storageBucket: 'instaclone-b0c32.appspot.com',
    iosBundleId: 'com.example.instalite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKOgwg9iKKSv5aBu-hOloQNrKttad3hbw',
    appId: '1:110447241239:ios:4094740c033ff8ad9b9452',
    messagingSenderId: '110447241239',
    projectId: 'instaclone-b0c32',
    storageBucket: 'instaclone-b0c32.appspot.com',
    iosBundleId: 'com.example.instalite.RunnerTests',
  );
}
